#ifndef __ACTIVEBSP_INSTRUCTIONS_H__
#define __ACTIVEBSP_INSTRUCTIONS_H__

namespace activebsp
{

typedef enum
{
    INSTRUCTION_STOP = 1,
    INSTRUCTION_CREATE_ACTOR,
    INSTRUCTION_DESTROY_ACTOR,
    INSTRUCTION_CALL_ACTOR,
    INSTRUCTION_REGISTER_FUTURE_DATA,
    INSTRUCTION_GET_FUTURE_DATA,
    INSTRUCTION_RELEASE_FUTURE,
    INSTRUCTION_STORE_RESULT,
    INSTRUCTION_STORE_RESULT_PART,
    INSTRUCTION_RELEASE_RESULT,
    INSTRUCTION_GET_RESULT_PARTS,
    INSTRUCTION_DISTRIBUTE_VECTOR,
    INSTRUCTION_PREFETCH,
    INSTRUCTION_FETCH

} instruction_t;

} // namespace activebsp

#endif // __ACTIVEBSP_INSTRUCTIONS_H__
